from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from models.document import Document
from schemas.document import DocumentCreate, DocumentInDB, DocumentUpdate
from database import get_db
from security import get_current_user
from models.user import User
from typing import List, Dict, Any

router = APIRouter()

@router.post("/", response_model=DocumentInDB)
def create_document(
    document: DocumentCreate,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user)
):
    db_document = Document(
        **document.dict(),
        user_id=user.id
    )
    db.add(db_document)
    db.commit()
    db.refresh(db_document)
    return db_document

@router.get("/", response_model=list[DocumentInDB])
def list_documents(
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user)
):
    return db.query(Document).filter(Document.user_id == user.id).all()

@router.delete("/{doc_id}")
def delete_document(
    doc_id: int,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user)
):
    document = db.query(Document).filter(
        Document.id == doc_id,
        Document.user_id == user.id
    ).first()
    if not document:
        raise HTTPException(404, "Document not found")
    
    db.delete(document)
    db.commit()
    return {"message": "Document deleted"}

@router.get("/{doc_id}", response_model=DocumentInDB)
def get_document(
    doc_id: int,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user)
):
    document = db.query(Document).filter(
        Document.id == doc_id,
        Document.user_id == user.id
    ).first()
    
    if not document:
        raise HTTPException(404, "Document not found")
    return document

@router.put("/{doc_id}", response_model=DocumentInDB)
def update_document(
    doc_id: int,
    document: DocumentUpdate,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user)
):
    db_document = db.query(Document).filter(
        Document.id == doc_id,
        Document.user_id == user.id
    ).first()
    
    if not db_document:
        raise HTTPException(404, "Document not found")
    
    for field, value in document.dict(exclude_unset=True).items():
        setattr(db_document, field, value)
    
    db.commit()
    db.refresh(db_document)
    return db_document

@router.post("/{doc_id}/generate", response_model=Dict[str, Any])
def generate_content(
    doc_id: int,
    prompt: Dict[str, Any],
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user)
):
    content_type = prompt.get("type", "paragraph")
    user_prompt = prompt.get("prompt", "")
    
    # In a real implementation, you would call your AI service here
    # For now, we'll just return dummy responses
    
    if content_type == "heading1":
        return {
            "content": f"Generated Heading 1 based on: {user_prompt}", 
            "type": "heading1"
        }
    elif content_type == "heading2":
        return {
            "content": f"Generated Heading 2 based on: {user_prompt}", 
            "type": "heading2"
        }
    elif content_type == "chat":
        return {
            "content": f"AI response to: {user_prompt}\n\nThis is a dummy response. In a real implementation, this would be generated by your AI model.",
            "type": "paragraph"
        }
    else:
        return {
            "content": f"AI-generated paragraph based on: {user_prompt}",
            "type": "paragraph"
        }
